name: NoteApp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.16.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    share_plus: ^4.0.6
    flutter_native_splash: ^2.2.2
    cupertino_icons: ^1.0.2
    hive: ^2.2.1
    hive_flutter: ^1.1.0
    intl: ^0.17.0
    auto_size_text: ^2.1.0

flutter_native_splash:
    color: '#1321E0'
    image: assets/photo.jpg

dev_dependencies:
    hive_generator: ^1.1.3
    build_runner: ^2.1.11

    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
